// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class 1SignupPageTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void 1SignupPage() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1552, 832));
    driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(6)")).click();
    driver.findElement(By.cssSelector(".MuiButton-root:nth-child(1)")).click();
    driver.findElement(By.id(":rh:")).click();
    driver.findElement(By.id(":rh:")).sendKeys("varnika@gmail.com");
    driver.findElement(By.id(":rj:")).click();
    driver.findElement(By.id(":rj:")).sendKeys("Varnika");
    driver.findElement(By.id(":rl:")).click();
    driver.findElement(By.id(":rl:")).sendKeys("varnika");
    driver.findElement(By.id(":rn:")).click();
    driver.findElement(By.id(":rn:")).sendKeys("varnika");
    driver.findElement(By.id(":rp:")).click();
    driver.findElement(By.id(":rp:")).sendKeys("256325859");
    driver.findElement(By.cssSelector(".MuiInputBase-multiline")).click();
    driver.findElement(By.id(":rr:")).sendKeys("Daiict");
    driver.findElement(By.id(":rt:")).click();
    driver.findElement(By.id(":rt:")).sendKeys("125632");
    driver.findElement(By.cssSelector(".MuiButton-fullWidth")).click();
    driver.findElement(By.id(":rl:")).click();
    driver.findElement(By.id(":rl:")).sendKeys("varnika@123");
    driver.findElement(By.id(":rn:")).click();
    driver.findElement(By.id(":rn:")).sendKeys("varnika@123");
    driver.findElement(By.cssSelector(".MuiButton-fullWidth")).click();
    js.executeScript("window.scrollTo(0,276)");
    driver.findElement(By.cssSelector(".MuiFormControl-root:nth-child(3) .MuiInputAdornment-root path")).click();
    driver.findElement(By.id(":rl:")).click();
    driver.findElement(By.id(":rl:")).sendKeys("Varnika@123");
    driver.findElement(By.cssSelector(".Mui-error:nth-child(2)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiFormControl-root:nth-child(4) .MuiInputAdornment-root path"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".MuiFormControl-root:nth-child(4) .MuiInputAdornment-root path")).click();
    driver.findElement(By.id(":rn:")).click();
    driver.findElement(By.id(":rn:")).sendKeys("Varnika@123");
    driver.findElement(By.id(":rp:")).click();
    driver.findElement(By.id(":rp:")).sendKeys("2563258595");
    driver.findElement(By.cssSelector(".MuiButton-fullWidth")).click();
    js.executeScript("window.scrollTo(0,276)");
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-text:nth-child(5)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".MuiButton-text:nth-child(5)")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id(":r1f:")).click();
  }
}
