// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class 4CartTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void 4Cart() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1552, 832));
    driver.findElement(By.cssSelector(".MuiButton-text:nth-child(5)")).click();
    driver.findElement(By.id(":rh:")).click();
    driver.findElement(By.id(":rh:")).sendKeys("padiakeyur@gmail.com");
    driver.findElement(By.id(":rj:")).click();
    driver.findElement(By.id(":rj:")).sendKeys("Keyur@123");
    driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(3)")).click();
    driver.findElement(By.id(":r1h:")).sendKeys("10");
    driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".MuiGrid-grid-sm-9")).click();
    driver.findElement(By.id(":r1r:")).click();
    driver.findElement(By.id(":r1r:")).click();
    driver.findElement(By.cssSelector(".MuiButton-fullWidth")).click();
    driver.findElement(By.id(":r25:")).click();
    driver.findElement(By.id(":r25:")).sendKeys("daiict");
    driver.findElement(By.id(":r27:")).click();
    driver.findElement(By.id(":r27:")).sendKeys("rAJKOT");
    driver.findElement(By.id(":r29:")).sendKeys("Gujarat");
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-sizeLarge"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id(":r2b:")).sendKeys("360007");
    driver.findElement(By.cssSelector(".MuiButton-sizeLarge")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".MuiButton-text")).click();
    js.executeScript("window.scrollTo(0,0)");
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiFab-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".MuiFab-root")).click();
    js.executeScript("window.scrollTo(0,64)");
  }
}
